# Generated by Django 2.1.4 on 2018-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='championData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('partype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a role (e.g. Support)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='championdata',
            name='tags',
            field=models.ManyToManyField(help_text='Select a role for this champion', to='parsed_data.Role'),
        ),
    ]
