# Generated by Django 2.1.4 on 2018-12-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20181219_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('partype', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
